config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "welcome#index"
  resources :signups
  resources :dashboards
    
  delete "logout", to: "dashboards#destroy"
  resources :logins

  resources :recipes do
    put :favorite, on: :member
  end

  resources :favorite_recipes
  
  resources :shops 
  
  resources :stashes

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite_recipe.rb
class FavoriteRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, optional: true

  has_many :favorite_recipes
  has_many :favorited_by, through: :favorite_recipes, source: :user
end

app/models/shop.rb
class Shop < ApplicationRecord
    has_many :reviews
    belongs_to :user, optional: true
    has_many :favorite_shops
    has_many :favorited_by, through: :favorite_shops, source: :user
end

app/models/stash.rb
class Stash < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, format: {with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address"}

  has_many :recipes
  has_many :favorite_recipes
  has_many :favorites, through: :favorite_recipes, source: :recipe

  has_many :stashes
  
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
    before_action :current_user
end

def index
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(user_name: params[:user_name])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to dashboards_path
    else
      flash[:alert] = "invalid log in information, please try again"
      render :new
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    recipe_name = params[:recipe][:name]
    recipe_type = params[:recipe][:recipe_type]
    recipe_instructions = params[:recipe][:instructions]
    recipe_site = params[:recipe][:recipe_url]

    Recipe.create(name: recipe_name, recipe_type: recipe_type, instructions: recipe_instructions, recipe_url: recipe_site)
    redirect_to recipes_path
  end

  def edit
    recipe_id = params[:id]
    @recipe = Recipe.find_by(id: recipe_id)
  end

  def update
    @recipe = Recipe.find(params[:id])
    new_recipe_name = params[:recipe][:name]
    new_recipe_type = params[:recipe][:recipe_type]
    new_recipe_instructions = params[:recipe][:instructions]
    new_recipe_site = params[:recipe][:recipe_url]

    @recipe.update(name: new_recipe_name, recipe_type: new_recipe_type, instructions: new_recipe_instructions, recipe_url: new_recipe_site)
    redirect_to recipes_path
  end

  def destroy
    recipe_id = params[:id]
    @recipe = Recipe.find_by(id: recipe_id)
    @recipe.destroy
    redirect_to recipes_path
  end

  def favorite
    @recipe = Recipe.find(params[:id])
    type = params[:type]
    if type == "favorite"
      current_user.favorites << @recipe
      redirect_to favorite_recipes_path	

    elsif type == "unfavorite"
      current_user.favorites.delete(@recipe)
      redirect_to favorite_recipes_path

    else
      redirect_to recipes_path

    end
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @shops = Shop.all
  end

  def show
    @shop = Shop.find(params[:id])
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      redirect_to shops_path
    else
      render :new
    end
  end

  def edit
    shop_id = params[:id]
    @shop = Shop.find_by(id: shop_id)  end

  def update
    @shop = Shop.find(params[:id])
    if @shop.update(shop_params)
      redirect_to shops_path
    else
      render :new
    end
  end

  def destroy
    shop_id = params[:id]
    @shop = Shop.find_by(id: shop_id)
    @shop.destroy
    redirect_to shops_path
  end

  def shop_params
    params.require(:shop).permit(:name, :shop_url, :street_address, :city, :country)
  end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to dashboards_path
    else
      render :new
    end
  end

  private

  def user_params
    params.required(:user).permit(:user_name, :email, :password, :password_confirmation)
  end
end

app/controllers/stashes_controller.rb
class StashesController < ApplicationController
    before_action :current_user 
 
    def index
        @user = User.find_by(id: session[:user_id])
        @stashes = Stash.all 
    end
     
    def new
        @stash = Stash.new
    end
     
    def create
        @stash = current_user.stashes.create(stash_params)
        if @stash.save
          redirect_to stashes_path
        else
          render :new
        end
    end

    def edit
        stash_id = params[:id]
        @stash = Stash.find_by(id: stash_id)
    end

    def update
        stash_id = params[:id]
        @stash = Stash.find_by(id: stash_id)
        @stash.update(stash_params)

        redirect_to stashes_path
    end

    def destroy
            stash_id = params[:id]
            @stash = Stash.find_by(id: stash_id)
            current_user.stashes.destroy(@stash)

        redirect_to stashes_path
    end
     
    private
     
    def stash_params
        params.require(:stash).permit(:tea_name, :tea_type, :purchased_at, :stash_amount, :notes, :user_id)
    end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/favorite_recipes_helper.rb
module FavoriteRecipesHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/helpers/stashes_helper.rb
module StashesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboards/index.html.erb
    <%= render partial: "shared/navbar" %>



    <h2>Welcome, <%= current_user_name %></h2>


<div class="row">
  <div class="column">
    <div class="card", onClick="location.href='<%= stashes_path %>'">
      <%= image_tag("tea_pics/Store-Loose-Leaf-Tea-Intro.jpg", class: "img-stash", width:"160px", height:"140px") %>
      <h3>Personal Tea Stash</h3>
    </div>
  </div>

  <div class="column">
      <div class="card", onClick="location.href='<%= favorite_recipes_path %>'">
      <%= image_tag("tea_pics/reyhaneh-mehrnejad-sm", class: "img-stash", width:"160px", height:"140px") %>
      <h3>Saved Recipes</h3>
   </div>
  </div>


  <div class="column">
    <div class="card", onClick="location.href='<%= shops_path %>'">
      <%= image_tag("tea_pics/tamara-malaniy-tea-shop.jpg", class: "img-stash", width:"160px", height:"140px") %>
      <h3>Find a Shop</h3>
   </div>
  </div>
                    
  <div class="column">
      <div class="card", onClick="location.href='<%= recipes_path %>'">
      <%= image_tag("tea_pics/may-lawrence-matcha-brownie.jpg", class: "img-stash", width:"160px", height:"140px") %>
      <h3>All Tea Recipes</h3>
   </div>
  </div>
  
</div>

app/views/logins/new.html.erb
<h2>Welcome back</h2>

<%= form_with url: logins_path do |f| %>
<div class="mb-3">
<%= f.label :username %>
<%= f.text_field :user_name, class: "form-control", placeholder: "MyUserName" %>
</div>
<div class="mb-3">
<%= f.label :password %>
<%= f.password_field :password, class: "form-control", placeholder: "password" %>
</div>
<%= f.submit "Log In" %>
<% end %>

app/views/signups/new.html.erb
<h2>Sign Up Form</h2>

<div id="col-1">

<%= form_with model: @user, url: signups_path do |f| %>
<% if @user.errors.any? %>
<div>
    <% @user.errors.full_messages.each do |message| %>
   <div><%= message %></div>
   <% end %>
</div>
<% end %>

<div class="mb-3">
<%= f.label :username %>
<%= f.text_field :user_name, class: "form-control", placeholder: "MyUserName" %>
</div>
<div class="mb-3">
<%= f.label :email %>
<%= f.email_field :email, class: "form-control", placeholder: "anyemail@yahoo.com" %>
</div>
<div class="mb-3">
<%= f.label :password %>
<%= f.password_field :password, class: "form-control", placeholder: "password" %>
</div>
<div class="mb-3">
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation, class: "form-control", placeholder: "password" %>
</div>
<%= f.submit "Sign Up" %>
<% end %>
</div>


<div id="col-2">
          <%= image_tag("tea_pics/jason-leung-sm.jpg") %>
</div>

app/views/welcome/index.html.erb

<div class="container-main">
<div class="hero-image">
      <%= image_tag("tea_pics/mike-kenneally-x0t6DiAg118-unsplash (1).jpg", class: "hero-image", height: "700px", width: "1000px") %>
 
  <div class="hero-text">
    <h1 style="font-size:50px">Welcome to the Tea App</h1>
    <p style="font-size:20px">A place to share your love of tea</p>
    <%= link_to "Sign Up", new_signup_path, class: "btn btn-light" %>
    <%= link_to "Log In", new_login_path, class: "btn btn-light" %>
  
  </div>
</div>
</div>
