config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "welcome#index"
  resources :signups
  resources :dashboards
    
  delete "logout", to: "dashboards#destroy"
  resources :logins

  resources :recipes do
    put :favorite, on: :member
  end

  resources :favorite_recipes
  
  resources :shops 
  
  resources :stashes

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite_recipe.rb
class FavoriteRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, optional: true

  has_many :favorite_recipes
  has_many :favorited_by, through: :favorite_recipes, source: :user
end

app/models/shop.rb
class Shop < ApplicationRecord
    has_many :reviews
    belongs_to :user, optional: true
    has_many :favorite_shops
    has_many :favorited_by, through: :favorite_shops, source: :user
end

app/models/stash.rb
class Stash < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, format: {with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address"}

  has_many :recipes
  has_many :favorite_recipes
  has_many :favorites, through: :favorite_recipes, source: :recipe

  has_many :stashes
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user_name
    User.find_by(id: session[:user_id]).user_name
  end
  helper_method :current_user_name

  def current_user
    User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
    before_action :current_user
end

def index
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(user_name: params[:user_name])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to dashboards_path
    else
      flash[:alert] = "invalid log in information, please try again"
      render :new
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    recipe_name = params[:recipe][:name]
    recipe_type = params[:recipe][:recipe_type]
    recipe_instructions = params[:recipe][:instructions]
    recipe_site = params[:recipe][:recipe_url]

    Recipe.create(name: recipe_name, recipe_type: recipe_type, instructions: recipe_instructions, recipe_url: recipe_site)
    redirect_to recipes_path
  end

  def edit
    recipe_id = params[:id]
    @recipe = Recipe.find_by(id: recipe_id)
  end

  def update
    @recipe = Recipe.find(params[:id])
    new_recipe_name = params[:recipe][:name]
    new_recipe_type = params[:recipe][:recipe_type]
    new_recipe_instructions = params[:recipe][:instructions]
    new_recipe_site = params[:recipe][:recipe_url]

    @recipe.update(name: new_recipe_name, recipe_type: new_recipe_type, instructions: new_recipe_instructions, recipe_url: new_recipe_site)
    redirect_to recipes_path
  end

  def destroy
    recipe_id = params[:id]
    @recipe = Recipe.find_by(id: recipe_id)
    @recipe.destroy
    redirect_to recipes_path
  end

  def favorite
    @recipe = Recipe.find(params[:id])
    type = params[:type]
    if type == "favorite"
      current_user.favorites << @recipe
      redirect_to favorite_recipes_path	

    elsif type == "unfavorite"
      current_user.favorites.delete(@recipe)
      redirect_to favorite_recipes_path

    else
      redirect_to recipes_path

    end
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @shops = Shop.all
  end

  def show
    @shop = Shop.find(params[:id])
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      redirect_to shops_path
    else
      render :new
    end
  end

  def edit
    shop_id = params[:id]
    @shop = Shop.find_by(id: shop_id)  end

  def update
    @shop = Shop.find(params[:id])
    if @shop.update(shop_params)
      redirect_to shops_path
    else
      render :new
    end
  end

  def destroy
    shop_id = params[:id]
    @shop = Shop.find_by(id: shop_id)
    @shop.destroy
    redirect_to shops_path
  end

  def shop_params
    params.require(:shop).permit(:name, :shop_url, :street_address, :city, :country)
  end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to dashboards_path
    else
      render :new
    end
  end

  private

  def user_params
    params.required(:user).permit(:user_name, :email, :password, :password_confirmation)
  end
end

app/controllers/stashes_controller.rb
class StashesController < ApplicationController
    before_action :current_user 
 
    def index
        @user = User.find_by(id: session[:user_id])
        @stashes = Stash.all 
    end
     
    def new
        @stash = Stash.new
    end
     
    def create
        @stash = current_user.stashes.create(stash_params)
        if @stash.save
          redirect_to stashes_path
        else
          render :new
        end
    end

    def edit
        stash_id = params[:id]
        @stash = Stash.find_by(id: stash_id)
    end

    def update
        stash_id = params[:id]
        @stash = Stash.find_by(id: stash_id)
        @stash.update(stash_params)

        redirect_to stashes_path
    end

    def destroy
            stash_id = params[:id]
            @stash = Stash.find_by(id: stash_id)
            current_user.stashes.destroy(@stash)

        redirect_to stashes_path
    end
     
    private
     
    def stash_params
        params.require(:stash).permit(:tea_name, :tea_type, :purchased_at, :stash_amount, :notes, :user_id)
    end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/favorite_recipes_helper.rb
module FavoriteRecipesHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/helpers/stashes_helper.rb
module StashesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/recipes/edit.html.erb
<%= render partial: "shared/navbar" %>

Edit recipe

<%= form_for @recipe do |f| %>
    <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
    </div>
    <div class="mb-3">
    <%= f.label :recipe_type %>
    <%= f.select :recipe_type, [[""], ["Drink"], ["Food"], ["Baked Good"]]%>
    </div>
    <div>
    <%= f.label :recipe_instructions %>
    <%= f.text_area :instructions, size: "50x10" %>
    </div>
    <div class="mb-3">
    <%= f.label :recipe_url %>
    <%= f.url_field :recipe_url, class: "form-control", placeholder: "Enter website address for recipe" %>
</div>
    <%= f.submit %>
<% end %>

app/views/recipes/index.html.erb
<%= render partial: "shared/navbar" %>

<h2>All Recipes</h2>


<% @recipes.each do |recipe| %>

    <div>
        <%= link_to recipe.name, recipe_path(recipe) %>
    </div>
<% end %>
<%= link_to "Add New Recipe", new_recipe_path %>

app/views/recipes/new.html.erb
<%= render partial: "shared/navbar" %>

Create new recipe

<%= form_for @recipe do |f| %>
    <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
    </div>
    <div class="mb-3">
    <%= f.label :recipe_type %>
    <%= f.select :recipe_type, [[""], ["Drink"], ["Food"], ["Baked Good"]]%>
    </div>
    <div>
    <%= f.label :recipe_instructions %>
    <%= f.text_area :instructions, size: "50x10" %>
    </div>
    <div class="mb-3">
    <%= f.label :recipe_url %>
    <%= f.url_field :recipe_url, class: "form-control", placeholder: "Enter website address for recipe" %>
</div>
    <%= f.submit %>
<% end %>

app/views/recipes/show.html.erb
<%= render partial: "shared/navbar" %>

<h2><%= @recipe.name %></h2> <%= @recipe.recipe_type %>

<div>
<%= link_to @recipe.recipe_url, @recipe.recipe_url, target: :_blank %> <br/>
<p>Recipe Instructions: <%= @recipe.instructions %> </p>
</div>

<% if current_user_name %>
  <%= link_to "favorite",   favorite_recipe_path(@recipe, type: "favorite"), method: :put %>
  <%= link_to "unfavorite", favorite_recipe_path(@recipe, type: "unfavorite"), method: :put %>
<% end %>

<%= link_to "Delete Recipe", recipe_path, method: :delete %>
<%= link_to "Edit Recipe", edit_recipe_path %>

<%= link_to "All Recipes", recipes_path %>

app/views/shops/edit.html.erb
<%= render partial: "shared/navbar" %>

Edit recipe

Create new shop

<%= form_for(@shop) do |f| %>
    <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
    </div>
    <div>
    <%= f.label :shop_url %>
    <%= f.url_field :shop_url, class: "form-control", placeholder: "Enter shop site" %>
    </div>
    <div>
    <%= f.label :street_address %>
    <%= f.text_field :street_address %>
    </div>
    <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
    </div>
    <div>
    <%= f.label :country %>
    <%= f.text_field :country %>
    </div>
    <%= f.submit %>
<% end %>

app/views/shops/index.html.erb
<%= render partial: "shared/navbar" %>
    <h2>Welcome to the shops page</h2>
    <h3>A place to share information on tea shops around the world</h3>
      <%= image_tag("tea_pics/petr-sevcovic-sm-resize.jpg", class: "center") %>

<% @shops.each do |shop| %>

    <div>
        <%= link_to shop.name, shop_path(shop) %>
    </div>
<% end %>
<%= link_to "Add New Shop", new_shop_path %>

app/views/shops/new.html.erb
<%= render partial: "shared/navbar" %>

Create new shop

<%= form_for(@shop) do |f| %>
    <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
    </div>
    <div>
    <%= f.label :shop_url %>
    <%= f.url_field :shop_url, class: "form-control", placeholder: "Enter shop site" %>
    </div>
    <div>
    <%= f.label :street_address %>
    <%= f.text_field :street_address %>
    </div>
    <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
    </div>
    <div>
    <%= f.label :country %>
    <%= f.text_field :country %>
    </div>
    <%= f.submit %>
<% end %>

app/views/shops/show.html.erb
<%= render partial: "shared/navbar" %>


<h2><%= @shop.name %></h2> 
<div>
<%= link_to @shop.shop_url, @shop.shop_url,target: :_blank %> <br/>
<p><%= @shop.street_address %>, <%= @shop.city %>, <%= @shop.country %></p>
</div>


<%= link_to "Delete Shop", shop_path, method: :delete %>
<%= link_to "Edit Shop", edit_shop_path %>

<%= link_to "All Shops", shops_path %>   

app/views/stashes/edit.html.erb
<%= render partial: "shared/navbar" %>

Edit an entry into your tea collection
 
<%= form_for @stash do |f| %>
    <div class="mb-3">
    <%= f.label :tea_name %>
    <%= f.text_field :tea_name %>
    </div>
    <div class="mb-3">
    <%= f.label :tea_type %>
    <%= f.text_field :tea_type %>
    </div>
    <div class="mb-3">
    <%= f.label :purchased_at %>
    <%= f.text_field :purchased_at %>
    </div>
    <div class="mb-3">
    <%= f.label :stash_amount %>
    <%= f.text_field :stash_amount %>
    </div>
    <div>
    <%= f.label :notes %>
    <%= f.text_area :notes, size: "50x10" %>
    </div>
    <%= f.submit %>
<% end %>

app/views/stashes/index.html.erb
<%= render partial: "shared/navbar" %>
 
<h2>View your personal tea collection</h2>
 
<% @user.stashes.each do |s| %>

<div class="row">
  <div class="column">
    <div class="card">
       Tea name: <%= s.tea_name %> <br/>
       Tea Type: <%= s.tea_type %> <br/>
       Purchased at: <%= s.purchased_at %> <br/>
       Amount in stash: <%= s.stash_amount %> <br/>
       Tea Notes: <%= s.notes %> <br/>
       <%= link_to "delete forever", stash_path(s), method: :delete %>
       <%= link_to "edit entry", edit_stash_path(s) %>
    </div>
</div>
</div>
<% end %> 
 
<%= link_to "Add Items", new_stash_path %>
 

app/views/stashes/new.html.erb
<%= render partial: "shared/navbar" %>

Add a new entry into your tea collection
 
<%= form_for @stash do |f| %>
    <div class="mb-3">
    <%= f.label :tea_name %>
    <%= f.text_field :tea_name %>
    </div>
    <div class="mb-3">
    <%= f.label :tea_type %>
    <%= f.text_field :tea_type %>
    </div>
    <div class="mb-3">
    <%= f.label :purchased_at %>
    <%= f.text_field :purchased_at %>
    </div>
    <div class="mb-3">
    <%= f.label :stash_amount %>
    <%= f.text_field :stash_amount %>
    </div>
    <div>
    <%= f.label :notes %>
    <%= f.text_area :notes, size: "50x10" %>
    </div>
    <%= f.submit %>
<% end %>